# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'invoiceScannerPlugin', :path => '../invoiceScannerPlugin'
end

# platform :ios, '16.2'
# workspace 'iosApp'
# use_frameworks! :linkage => :static
#
# target 'iosApp' do
#
#   pod 'GoogleMLKit/BarcodeScanning'
#   pod 'GoogleMLKit/FaceDetection'
#
# end